import { Component, OnInit, TemplateRef, ViewChild } from '@angular/core';
import { BsModalService } from 'ngx-bootstrap/modal';
import { TranslateService } from '@ngx-translate/core';
import { BsModalRef } from 'ngx-bootstrap/modal';
import { Observable, of, Subscription } from 'rxjs';
import { catchError, map, switchMap, take, tap } from 'rxjs/operators';
import { ClassType } from 'class-transformer/ClassTransformer';
import { find, first, get, includes, isNil } from 'lodash';
import { AObject, FilterOperator, PlatformConstants } from '@congarevenuecloud/core';
import { CartService, Cart, PriceService, CartResult, FieldFilter, SummaryGroup, LocalCurrencyPipe, DateFormatPipe, AccountService, StorefrontService, DisplayColumn, DisplayColumnSection } from '@congarevenuecloud/ecommerce';
import { TableOptions, TableColumn, TableAction, ExceptionService, DisplayColumnService } from '@congarevenuecloud/elements';

@Component({
    selector: 'app-cart-list',
    templateUrl: './cart-list.component.html',
    styleUrls: ['./cart-list.component.scss'],
    standalone: false
})
export class CartListComponent implements OnInit {
  type = Cart;

  modalRef: BsModalRef;
  message: string;
  loading: boolean = false;
  cart: Cart;
  view$: Observable<CartListView>;
  cartAggregate$: Observable<any>;
  isCloneCart: boolean = false;
  subscription: Subscription;

  // Columns rendered in the cart list, from the 'Cart List' section of the displayColumns API;
  // empty means the storefront has no configuration, so the built-in columns are used.
  private configuredColumns: Array<DisplayColumn> = [];

  @ViewChild('effectiveDateTemplate') effectiveDateTemplate: TemplateRef<any>;
  @ViewChild('createCartTemplate') createCartTemplate: TemplateRef<any>;

  constructor(private cartService: CartService, public priceService: PriceService, private currencyPipe: LocalCurrencyPipe, private dateFormatPipe: DateFormatPipe,
    private modalService: BsModalService, private translateService: TranslateService, private exceptionService: ExceptionService, private accountService: AccountService,
    private storefrontService: StorefrontService, private displayColumnService: DisplayColumnService) { }

  ngOnInit() {
    // Read the column configuration once, then keep reloading the view as the account changes.
    this.subscription = this.storefrontService.getStorefront().pipe(
      take(1),
      switchMap((storefront) => {
        const flow = get(storefront, 'DefaultFlow') || 'system';
        return this.storefrontService.getStorefrontDisplayColumns(flow, get(storefront, 'Id'));
      }),
      catchError(() => of<Array<DisplayColumn>>([])),
      tap((response) => this.configuredColumns = this.displayColumnService.columnsForSection(response, DisplayColumnSection.CartList)),
      switchMap(() => this.accountService.getCurrentAccount())
    ).subscribe(() => this.loadView());
  }

  // Adds the cart specific cells on top of the shared date and currency formatting. IsActive and
  // TotalAmount are derived rather than stored, so they always need their own callback.
  private cartColumnValue(column: DisplayColumn) {
    if (get(column, 'FieldName') === 'IsActive') {
      return (record: Cart) => this.isActiveCart(record) ? of('Yes') : of('No');
    }
    if (get(column, 'FieldName') === 'TotalAmount') {
      return (record: Cart) => this.getCartTotal(record);
    }
    return this.displayColumnService.formatColumnValue(column);
  }

  /** @ignore */
  private isActiveCart(record: Cart): boolean {
    return this.cartService.getCurrentCartId() === record.Id && !isNil(record.ActivationDate);
  }

  // The built-in cart list columns, used when the storefront has no configuration.
  private getDefaultColumns(): Array<TableColumn> {
    return [
      {
        prop: 'AutoGeneratedNumber',
        enableRouteLink: true
      },
      {
        prop: 'Name',
        showPopover: true,
        label: 'COMMON.NAME'
      },
      {
        prop: 'CreatedDate',
        label: 'CUSTOM_LABELS.CREATED_DATE',
        value: (record: Cart) => this.getDateFormat(record, 'CreatedDate')
      },
      {
        prop: 'CreatedBy.Name',
        label: 'CUSTOM_LABELS.CREATED_BY'
      },
      {
        prop: 'IsActive',
        label: 'CUSTOM_LABELS.IS_ACTIVE',
        sortable: false,
        value: (record: Cart) => this.isActiveCart(record) ? of('Yes') : of('No')
      },
      {
        prop: 'TotalAmount',
        label: 'CUSTOM_LABELS.TOTAL_AMOUNT',
        sortable: false,
        value: (record: Cart) => this.getCartTotal(record)
      },
      {
        prop: 'Status'
      },
      {
        prop: 'NumberOfItems'
      }
    ];
  }

  loadView() {
    let tableOptions = {} as CartListView;
    this.view$ = this.cartService.getMyCart()
      .pipe(
        take(1),
        map(() => {
          const columns = this.displayColumnService.toTableColumns(this.configuredColumns, this.getDefaultColumns(), (column: DisplayColumn) => this.cartColumnValue(column));
          tableOptions = {
            tableOptions: {
              stickyColumnCount: 1,
              // The first column stays pinned, so it follows whatever the configuration puts first.
              stickyColumns: columns.slice(0, 1),
              columns: columns,
              lookups: ['SummaryGroups'],
              actions: [
                {
                  enabled: true,
                  icon: 'fa-check',
                  massAction: false,
                  label: 'MY_ACCOUNT.CART_LIST.SET_ACTIVE',
                  theme: 'primary',
                  validate: (record: Cart) => this.canActivate(record),
                  action: (recordList: Array<Cart>) => this.cartService.setCartActive(first(recordList), true)
                    .pipe(
                      catchError(err => {
                        this.loadView();
                        throw err;
                      }),
                      map(res => {
                        this.exceptionService.showSuccess('SUCCESS.CART.ACTIVATED');
                        this.loadView();
                      })
                    ),
                  disableReload: true
                } as TableAction,
                {
                  enabled: true,
                  icon: 'fa-calendar',
                  massAction: false,
                  label: 'CART.SET_EFFECTIVE_DATE',
                  theme: 'primary',
                  validate: (record: Cart) => this.canSetEffectiveDate(record),
                  action: (recordList: Array<Cart>) => this.showEffectiveDateModal(first(recordList), this.effectiveDateTemplate),
                  disableReload: true
                } as TableAction,
                {
                  enabled: true,
                  icon: 'fa-trash',
                  massAction: true,
                  label: 'COMMON.DELETE',
                  theme: 'danger',
                  validate: (record: Cart) => this.canPerformAction(record),
                  action: (recordList: Array<Cart>) => this.cartService.deleteCart(recordList)
                    .pipe(
                      map(res => {
                        this.exceptionService.showSuccess('SUCCESS.CART.DELETED');
                        this.getCartAggregate();
                      }),
                      catchError(err => {
                        this.getCartAggregate();
                        throw err;
                      })
                    ),
                  disableReload: true
                } as TableAction,
                {
                  enabled: true,
                  icon: 'fa-clone',
                  massAction: false,
                  label: 'COMMON.CLONE',
                  theme: 'primary',
                  validate: (record: Cart) => this.canPerformAction(record),
                  action: (recordList: Array<Cart>) => this.newCart(this.createCartTemplate, first(recordList)),
                  disableReload: true
                } as TableAction,
              ],
              highlightRow: (record: Cart) => of(this.cartService.getCurrentCartId() === record.Id && !isNil(record.ActivationDate)),
              filters: this.getFilters(),
              routingLabel: 'carts'
            },
            type: Cart
          }
          this.getCartAggregate();
          return tableOptions;
        })
      );
  }


  private getCartAggregate(): Observable<CartResult> {
    return this.cartAggregate$ = this.cartService.getCartList(this.getFilters()).pipe(take(1), map(res => res));
  }

  /**
   * Creates new cart for logged in user based on input.
   * @param template Modal input for taking user inputs for new cart.
   */
  newCart(template: TemplateRef<any>, sourceCart?: Cart) {
    this.cart = new Cart();
    if (sourceCart) {
      this.isCloneCart = true;
      this.cart = sourceCart;
      this.cart.Name = `Clone of ${sourceCart.Name}`
    } else {
      this.isCloneCart = false;
    }
    this.message = null;
    this.modalRef = this.modalService.show(template);
    return of(null);
  }

  getDateFormat(record: Cart, field: string, dateTimeFormat: string = 'ShortDatePattern'): Observable<string> {
    const dateValue = get(record, field);
    if (!dateValue) return of('');
    return this.dateFormatPipe.transform(dateValue, dateTimeFormat);
  }

  createCart() {
    this.loading = true;
    this.cartService.createNewCart(this.cart).pipe(take(1)).subscribe(
      res => {
        this.loading = false;
        this.modalRef.hide();
        this.exceptionService.showSuccess('SUCCESS.CART.NEW_CART_CREATED');
        this.loadView();
      },
      err => {
        this.loading = false;
        this.translateService.stream('MY_ACCOUNT.CART_LIST.CART_CREATION_FAILED').subscribe((val: string) => {
          this.message = val;
        });
      }
    );
  }
  cloneCart() {
    this.loading = true;
    delete this.cart.Status;
    this.cartService.cloneCart(this.cart.Id, this.cart, false, true).pipe(take(1)).subscribe(
      res => {
        this.loading = false;
        this.modalRef.hide();
        this.exceptionService.showSuccess('SUCCESS.CART.CLONE_CART_SUCCESS');
        this.loadView();
      },
      err => {
        this.loading = false;
        this.translateService.stream('MY_ACCOUNT.CART_LIST.CART_CLONE_FAILED').pipe(take(1)).subscribe((val: string) => {
          this.message = val;
        });
      }
    );
  }

  handleFormSubmit() {
    if (this.isCloneCart) {
      this.cloneCart();
    } else {
      this.createCart();
    }
  }

  getCartTotal(currentCart: Cart): Observable<string> {
    return this.currencyPipe.transform(get(find(get(currentCart, 'SummaryGroups', []), r => r.LineType === 'Grand Total'), 'NetPrice'));
  }


  canPerformAction(cart: Cart) {
    return (cart.Status !== 'Finalized');
  }

  canSetEffectiveDate(cart: Cart) {
    return !includes(['Finalized', 'Superseded'], get(cart, 'Status'));
  }

  canActivate(cartToActivate: Cart) {
    return (this.cartService.getCurrentCartId() !== cartToActivate.Id && !includes(['Finalized', 'Superseded'], get(cartToActivate, 'Status')));
  }

  showEffectiveDateModal(cart: Cart, template: TemplateRef<any>) {
    this.cart = cart;
    this.modalRef = this.modalService.show(template);
    return of(null);
  }

  setEffectiveDate() {
    this.loading = true;
    this.cartService.setEffectiveDate(this.cart).pipe(take(1)).subscribe(res => {
      this.loading = false;
      this.modalRef.hide();
      this.exceptionService.showSuccess('SUCCESS.CART.EFFECTIVE_DATE');
    },
      err => {
        this.loading = false;
        this.translateService.stream('MY_ACCOUNT.CART_LIST.EFFECTIVE_DATE_NOT_UPDATED').subscribe((val: string) => {
          this.message = val;
        });
      })
  }

  getFilters(): Array<FieldFilter> {
    return [
      {
        field: 'Account.Id',
        value: localStorage.getItem(PlatformConstants.ACCOUNT),
        filterOperator: FilterOperator.EQUAL
      },
      {
        field: 'UseType',
        value: 'Shadow',
        filterOperator: FilterOperator.NOT_EQUAL
      },
      {
        field: 'BusinessObjectType',
        value: 'FavoriteConfiguration',
        filterOperator: FilterOperator.NOT_EQUAL
      }
    ] as Array<FieldFilter>;
  }

  ngOnDestroy() {
    if (!isNil(this.subscription))
      this.subscription.unsubscribe();
  }
}

interface CartListView {
  tableOptions: TableOptions;
  type: ClassType<AObject>;
}
